extractors:
  ops:
    keys:
      MboxV4: "C45D057199DDBBEE29A16DC7ADBFA43F00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000A00"
      MboxV5: "608A3F2D686BD423510CD095BB40E97600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000A00"
      MboxV6: "AA69829E5DDEB13D30BB81A34665A3E100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000A00"
  ofp_mtk:
    keys:
      - ObsKey: "67657963787565E837D226B69A495D21"
        AesKey: "F6C50203515A2CE7D8C3E1F938B7E94C"
        AesIv: "42F2D5399137E2B2813CD8ECDF2F4D72"

      - ObsKey: "9E4F32639D21357D37D226B69A495D21"
        AesKey: "A3D8D358E42F5A9E931DD3917D9A3218"
        AesIv: "386935399137416B67416BECF22F519A"

      - ObsKey: "892D57E92A4D8A975E3C216B7C9DE189"
        AesKey: "D26DF2D9913785B145D18C7219B89F26"
        AesIv: "516989E4A1BFC78B365C6BC57D944391"

      - ObsKey: "27827963787265EF89D126B69A495A21"
        AesKey: "82C50203285A2CE7D8C3E198383CE94C"
        AesIv: "422DD5399181E223813CD8ECDF2E4D72"

      - ObsKey: "3C4A618D9BF2E4279DC758CD535147C3"
        AesKey: "87B13D29709AC1BF2382276C4E8DF232"
        AesIv: "59B7A8E967265E9BCABE2469FE4A915E"

      - ObsKey: "1C3288822BF824259DC852C1733127D3"
        AesKey: "E7918D22799181CF2312176C9E2DF298"
        AesIv: "3247F889A7B6DECBCA3E28693E4AAAFE"

      - ObsKey: "1E4F32239D65A57D37D2266D9A775D43"
        AesKey: "A332D3C3E42F5A3E931DD991729A321D"
        AesIv: "3F2A35399A373377674155ECF28FD19A"

      - ObsKey: "122D57E92A518AFF5E3C786B7C34E189"
        AesKey: "DD6DF2D9543785674522717219989FB0"
        AesIv: "12698965A132C76136CC88C5DD94EE91"

      - AesKey: "ab3f76d7989207f2"
        AesIv: "2bf515b3a9737835"
  ofp_qualcomm:
    keys:
      V1.4.17/1.4.27:
        Mc: "27827963787265EF89D126B69A495A21"
        UserKey: "82C50203285A2CE7D8C3E198383CE94C"
        Ivec: "422DD5399181E223813CD8ECDF2E4D72"
      V1.6.17:
        Mc: "E11AA7BB558A436A8375FD15DDD4651F"
        UserKey: "77DDF6A0696841F6B74782C097835169"
        Ivec: "A739742384A44E8BA45207AD5C3700EA"
      V1.5.13:
        Mc: "67657963787565E837D226B69A495D21"
        UserKey: "F6C50203515A2CE7D8C3E1F938B7E94C"
        Ivec: "42F2D5399137E2B2813CD8ECDF2F4D72"
      V1.6.6/1.6.9/1.6.17/1.6.24/1.6.26/1.7.6:
        Mc: "3C2D518D9BF2E4279DC758CD535147C3"
        UserKey: "87C74A29709AC1BF2382276C4E8DF232"
        Ivec: "598D92E967265E9BCABE2469FE4A915E"
      V1.7.2:
        Mc: "8FB8FB261930260BE945B841AEFA9FD4"
        UserKey: "E529E82B28F5A2F8831D860AE39E425D"
        Ivec: "8A09DA60ED36F125D64709973372C1CF"
      V2.0.3:
        Mc: "E8AE288C0192C54BF10C5707E9C4705B"
        UserKey: "D64FC385DCD52A3C9B5FBA8650F92EDA"
        Ivec: "79051FD8D8B6297E2E4559E997F63B7F"
log:
  handlers:
    - sink: !func sys.stdout
      format: '| <lvl>{level}</lvl> | <lvl>{message}</lvl>'
      level: 'INFO'
      enqueue: false
      colorize: true
